create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  ticket_id text not null unique,
  status text not null default 'received',
  name text not null,
  phone text not null,
  address text not null,
  category text not null,
  description text not null default '',
  latitude double precision not null,
  longitude double precision not null,
  image_file text,
  image_url text,
  audio_file text,
  audio_url text,
  audio_transcript text,
  created_at timestamptz not null default now()
);

alter table public.incidents enable row level security;

insert into storage.buckets (id, name, public)
values
  ('issue-audio', 'issue-audio', true),
  ('issue-photos', 'issue-photos', true)
on conflict (id) do update set public = excluded.public;

create policy "Public media can be viewed"
on storage.objects for select
to public
using (bucket_id in ('issue-audio', 'issue-photos'));

-- The FastAPI server uses the Supabase service-role key server-side.
-- Do not expose that key in browser code.
